name: adsc3910-project-group-5
channels:
  - conda-forge
dependencies:
  - python=3.11
  - black
  - flake8
  - isort
  - pip
  - pymongo
  - seaborn
  - matplotlib
  - pyspark
  - pip:
    - python-dotenv
    - -e .
